//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_custom : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean grip
        {
            get
            {
                return SteamVR_Actions.custom_grip;
            }
        }
        
        public virtual SteamVR_Action_Boolean menu
        {
            get
            {
                return SteamVR_Actions.custom_menu;
            }
        }
        
        public virtual SteamVR_Action_Boolean trigger
        {
            get
            {
                return SteamVR_Actions.custom_trigger;
            }
        }
        
        public virtual SteamVR_Action_Pose pose
        {
            get
            {
                return SteamVR_Actions.custom_pose;
            }
        }
        
        public virtual SteamVR_Action_Boolean forward
        {
            get
            {
                return SteamVR_Actions.custom_forward;
            }
        }
        
        public virtual SteamVR_Action_Boolean backward
        {
            get
            {
                return SteamVR_Actions.custom_backward;
            }
        }
        
        public virtual SteamVR_Action_Boolean left
        {
            get
            {
                return SteamVR_Actions.custom_left;
            }
        }
        
        public virtual SteamVR_Action_Boolean right
        {
            get
            {
                return SteamVR_Actions.custom_right;
            }
        }
        
        public virtual SteamVR_Action_Boolean center
        {
            get
            {
                return SteamVR_Actions.custom_center;
            }
        }
    }
}
